### ISSUE TITLE
Example with Firebase/Google cloud function

### ISSUE THREAD

**Issue by SamyPesse** [googleapis/nodejs-tasks#224]
I've started looking into Cloud Task for our application which run on Firebase/Google Cloud Functions + PubSub. The main reason we want to use Cloud Task over PubSub is to control the concurrency of a queue.

It looks like Cloud Task can work with a cloud function since it uses an HTTP request to dispatch the task. Can you confirm that it's the case ?

It may be great to have an example of a Firebase Functions setup to use Cloud Task.

**Comment by philberg** [comment]
@SamyPesse check out my question and the answer in #203 .

It requires the latest alpha version, which you need you request access to

**Comment by philberg** [comment]
Apparently it's now in open beta!
https://cloud.google.com/tasks/docs/creating-http-target-tasks

**Comment by averikitsch** [comment]
Hi @SamyPesse, we now have a [tutorial using Cloud Tasks with Cloud Functions](https://cloud.google.com/tasks/docs/tutorial-gcf).
