### ISSUE TITLE
Samples Folder Issues

### ISSUE THREAD

**Issue by grant** [googleapis/nodejs-tasks#227]
There are a few issues when navigating to this repo and trying out the `samples/`.

- **Before you begin** ("Before running the samples, make sure you've followed the steps outlined in Using the client library."
  - The link to [`"Using the client library"`](https://github.com/googleapis/nodejs-tasks#using-the-client-library) simply links to code. There are no steps. How do I follow them?
- **Samples** > **Create Http Task**
  - Nit: HTTP should be capitalized in the title as it is an acronym.
  - **Usage**
    - `node createHttpTask.js`: This does not work and returns the error: `TypeError: Cannot read property 'charCodeAt' of undefined`. After looking at the code, it seems like there are missing arguments.
  - Opening in Cloud Shell and running the command doesn't work either. (We also need to first `cd` into the right directory. Maybe this could be configured?)
- At this point I gave up on trying the sample and decided to report this bug. It would be nice if you just `clone`, `cd samples`, `npm i`, `node createHttpTasks.js` assuming your Cloud Project is set up.

#### Environment details

  - OS: OSX
  - Node.js version: 11.6
  - npm version: 6.5
  - `@google-cloud/tasks` version: 1.0.0

**Comment by JustinBeckwith** [comment]
Thanks for the issue!  Let's take these one at a time:

*Before you begin*: This isn't specific to this library.  It's common to how we generate the `samples/README.md` file, so I created this to track that discussion: https://github.com/googleapis/google-cloud-node/issues/2927

*HTTP should be capitalized* Just to keep issue tracking tidy, I created https://github.com/googleapis/nodejs-tasks/issues/228 to track updating the title of the sample.  

*Usage for node createHttpTask.js*: More keeping issue tracking tidy: https://github.com/googleapis/nodejs-tasks/issues/229

On this point:

> At this point I gave up on trying the sample and decided to report this bug. It would be nice if you just clone, cd samples, npm i, node createHttpTasks.js assuming your Cloud Project is set up.

I hear you.  However - I believe optimizing for the CLI experience with the snippets was a non-goal (@jmdobry can share more about that).  We should make sure we express usage correctly in the README, but maintaining the full `yargs` arg validation was a ton of code that got out of date really easily.  We mostly expect these samples to be copy/pasted, which comes with the bug commented out TODO section telling the developer which fields to replace.

**Comment by grant** [comment]
Thanks for splitting the issues.

For the CLI point, I'm just looking for a way to run the samples. Instructions for running the tests are not documented (#231). I'm not sure what I should be doing otherwise.

I could just copy/paste and debug on my own, but since there's this repo, it would be cool if I could just try the samples here for a head start.

Will close this in favor of the smaller issues we've created.
