### ISSUE TITLE
Samples should include usage metadata

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/nodejs-tasks#229]
Many of the samples in this repo require arguments to be passed on the command line to work properly.  To express that in the README, we should be use sample metadata comments.  In any sample file you can add metadata like this:

```js
// sample-metadata:
//   title: Export Assets
//   description: Export asserts to specified dump file path.
//   usage: node exportAssets.js <gs://my-bucket/my-assets.txt>
```

That will ensure the correct usage is shown in the README for the user. 

------
Originally reported by @grant in https://github.com/googleapis/nodejs-tasks/issues/227

**Comment by grant** [comment]
For example, the real usage was more like this:
```sh
node createHttpTask.js project-id us-central1 my-queue http://my-url
```

Not
```sh
node createHttpTask.js
```
