### ISSUE TITLE
Create HTTP Target tasks fails due to URL issue

### ISSUE THREAD

**Issue by SaugataDutta** [googleapis/nodejs-tasks#247]
I am trying to create a task using the sample code provided here: https://cloud.google.com/tasks/docs/creating-http-target-tasks

But it keeps failing with the below error.

Console.log(task) prints this

> > {
>   httpRequest: {
>     httpMethod: 'POST',
>     url: 'https://abc-test.host/resource/v1/',
>     body: 'eyJ2YXJpYW50SWQiOiI0Mzc1Iiwib2ZmZXJpbmdJZCI6IjQzNzUiLCJwcmljZURhdGEiOlt7ImN1cnJlbmN5Q29kZSI6IkNMUCIsImNvdW50cnlDb2RlIjoiQ0wiLCJ2YWx1ZSI6MzcwLCJpc1B1Ymxpc2hlZCI6dHJ1ZSwicHJlY2lzaW9uIjowfV0sInNvdXJjZVVwZGF0ZWRBdCI6IjIwMTgtMTAtMDFUMjM6MjY6NTUuMDAwWiIsInByaWNlVHlwZSI6IlBULVRFU1QtMDEiLCJwcmljZUdyb3VwIjoiUEctVEVTVC0wMSJ9'
>   },
>   scheduleTime: {
>     seconds: 1561014172.82
>   }
> }

   
`const` [response] = await client.createTask(request);`  throws the below error.

> TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object
>     at Url.parse (url.js:154:11)
>     at Object.urlParse [as parse] (url.js:148:13)
>     at ClientHttp2Stream.request.on (/Users/Saugata/CatalogProjects/price-service/node_modules/@opencensus/instrumentation-http2/build/src/http2.js:105:34)
>     at ClientHttp2Stream.contextWrapper (/Users/Saugata/CatalogProjects/price-service/node_modules/@opencensus/core/build/src/internal/cls-ah.js:72:28)
>     at ClientHttp2Stream.emit (events.js:194:15)
>     at endReadableNT (_stream_readable.js:1125:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

#### Environment details
"@google-cloud/tasks": "^1.1.1",
"node": ">=10.*" (10.15.3)

Any help is appreciated.

Thanks!
Saugata

**Comment by SaugataDutta** [comment]
Upon checking little further, it seems that there is an issue at this line , the `authority` is an object and `url.parse` expects a string.

> const host = url.parse(authority).host;

at ClientHttp2Stream.request.on (/Users/Saugata/CatalogProjects/price-service/node_modules/@opencensus/instrumentation-http2/build/src/http2.js:105:34)

I modified this line locally to 

> const host = authority.host;

or this

> const host = url.parse(JSON.stringify(authority)).host;

**Comment by averikitsch** [comment]
Hi @SaugataDutta - I am unable to recreate this error. How are you running this sample, specifically how are you constructing or passing the url?

**Comment by SaugataDutta** [comment]
@averikitsch  The problem is not the url that I am passing to the task, the issue is with the url that is formed in the grpc module to create a task. I will attach the entire code snippet.

**Comment by SaugataDutta** [comment]
[taskSchedulerService.js.zip](https://github.com/googleapis/nodejs-tasks/files/3315502/taskSchedulerService.js.zip)

**Comment by averikitsch** [comment]
HTTP targets is a beta feature. Please make sure you are using the correct library version, [sample](https://github.com/googleapis/nodejs-tasks/blob/master/samples/createHttpTask.js#L36).

**Comment by SaugataDutta** [comment]
@averikitsch I tried with v2beta3 as well, but it gives the same error.

**Comment by SaugataDutta** [comment]
This is working fine now. Not sure what was wrong, probably a stale version of a sub-dependency in local cache. hence, closing the .
