### ISSUE TITLE
Payload on HTTP Request target always empty

### ISSUE THREAD

**Issue by jkarst** [googleapis/nodejs-tasks#248]
#### Environment details

  - OS: Windows 10 64 bit 
  - Node.js version: 10.15.3
  - npm version: 6.4.1
  - `@google-cloud/tasks` version: v2Beta3

#### Steps to reproduce

  1. Download the samples from this repo
  2. Run createHttpTask.js with a real project ID and queue name and set a delay
  3. Go to Google Cloud Tasks console to view created task
  4. Note that the payload is always empty

Alternatively, use a real URL target and note that the request.body is always empty on the target request handler (I'm using Firebase cloud functions).

**Comment by SaugataDutta** [comment]
Can you share the code that receives the payload? If you are using `express`, you need to add `body-parser` as shown in this sample code  - https://cloud.google.com/tasks/docs/creating-appengine-handlers

**Comment by jkarst** [comment]
Hi @SaugataDutta, thanks for the quick reply.

I've tested this using a basic Firebase cloud [http on request function](https://firebase.google.com/docs/functions/http-events), which I can share later when I'm at my dev machine.  It basically logs the request.body, which is always null.

That said, shouldn't the payload in the Google Tasks console show something when you create a cloud task with a payload?

**Comment by averikitsch** [comment]
> Thank You for this post, this is a bug in the existing Cloud Tasks UI and we are in the process of fixing this bug.
In the meantime the correct HTTP method of the task can be determined by running the following command:
gcloud beta tasks describe
https://cloud.google.com/sdk/gcloud/reference/beta/tasks/describe
The above command will show the correct HTTP method for the task.

[Original Post on StackOverflow](https://stackoverflow.com/questions/56259885/google-cloud-tasks-always-set-httpmethod-to-get-when-using-httprequest-as-payloa)

**Comment by SaugataDutta** [comment]
I see the same issue, I don't receive the body in the target. Please find below the output of 
`gcloud beta tasks describe  --queue=price-scheduler-queue 7986826783942521741`

> gcloud beta tasks describe  --queue=price-scheduler-queue 7986826783942521741
> createTime: '2019-06-25T15:13:43Z'
> dispatchDeadline: 600s
> httpRequest:
>   headers:
>     User-Agent: Google-Cloud-Tasks
>     traceHeaders: '[object Object]'
>   httpMethod: POST
>   oidcToken:
>     audience: https://fcf2384a.ngrok.io/tasks/v1/price
>     serviceAccountEmail: scheduler-service@core-catalog-dev.iam.gserviceaccount.com
>   url: https://fcf2384a.ngrok.io/tasks/v1/price
> name: projects/core-catalog-dev/locations/us-central1/queues/price-scheduler-queue/tasks/7986826783942521741
> scheduleTime: '2019-06-25T15:15:00Z'
> view: BASIC

**Comment by averikitsch** [comment]
@SaugataDutta you're right. You can use the `getTask` method passing the request object with the full task name and responseView 'FULL'.
```
const request = {
    name: 'projects/PROJECT_ID/locations/LOCATION_ID/queues/QUEUE_ID/tasks/TASK_ID',
    responseView: 'FULL'
  };

  const [response] = await client.getTask(request);
```

I also expect this is a body parser issue. The default Content-type is "application/octet-stream"; however, since it is null make sure you are adding it to your request. It should look like:
```
{ httpRequest:
   { httpMethod: 'POST',
     url: 'https://example.com/taskhandler',
     body: 'SGVsbG8sIFdvcmxkIQ==' },
 }
```

**Comment by jkarst** [comment]
I figured it out - at least for my problem.

The key is setting an HTTP header for the content-type.  It needs to be manually set to application/octet-stream

So using the Node API, this works for me now:

```
  const {v2beta3} = require('@google-cloud/tasks');
  const client = new v2beta3.CloudTasksClient();

  const parent = client.queuePath('YOUR-PROJECT-ID', 'us-central1', 'YOUR-QUEUE')
 
  const task = {
    httpRequest: {
      httpMethod: 'POST',
      url: YOUR-HTTP-TARGET,
      body: Buffer.from('hello').toString('base64'),
      headers: {
          'content-type': 'application/octet-stream'
      }
    }
  }

  const request = {
    parent: parent,
    task: task
  }

  client.createTask(request).then( task => console.log(`Task ${task[0].name} created`)).catch( error => console.log(error))

```

Then on the HTTP target side, you just read the rawBody (this is from a Firebase cloud function)

`    console.log (Buffer.from(request.rawBody, 'base64').toString('ascii'))
`

**Comment by jkarst** [comment]
@averikitsch 

Is my solution the correct behaviour here?  If so, then the samples and documentation needs to be updated.

**Comment by averikitsch** [comment]
You shouldn't have to manually se the content-type to octet-stream. How you are parsing the request body in your Firebase function is solving your problem.

**Comment by jkarst** [comment]
I'm not sure on that.

When I use the gcloud CLI function or the API and don't set a header, then no content-type header is set in the request:

![image](https://user-images.githubusercontent.com/3164825/60118527-89fdda80-974a-11e9-9372-25a4ca6652ef.png)

When this is sent from Google Tasks to the HTTP target, the rawBody property isn't available. 

However, when I set the header manually, the request looks like this: 

![image](https://user-images.githubusercontent.com/3164825/60118500-81a59f80-974a-11e9-85c9-224b916ce4e0.png)

...then the rawBody property is available.

It seems to me that some content-type header must be set for the bodyParser to work, and this content-type isn't being set automatically.   So the solution is to set the content-type header.

**Comment by chachew** [comment]
I too can ONLY get this to work by setting the header to `application/octet-stream`

**Comment by darthmeme** [comment]
@averikitsch - @jkarst's solution to adding the header manually was also the only way this worked for us.

**Comment by mtwichel** [comment]
Chiming in - I also had to use @jkarst's solution adding the header manually.

**Comment by kirillgroshkov** [comment]
Header worked for me too, but I used `{ 'content-type': 'Application/json' }` directly, and it brought json directly to my `req.body` (in express)

**Comment by summer-ji-eng** [comment]
Double check that the payload work as expected with headers and without headers.

<img width="512" alt="Screen Shot 2020-06-18 at 10 37 48 AM" src="https://user-images.githubusercontent.com/6378676/85082529-0a9bbf00-b184-11ea-8a4b-3c82494e9e8a.png">

But try to add header if you have same issue and let us know. 
`    headers: {
      'content-type': 'application/octet-stream',
    },
`

I am kindly close it. But feel free to open an issue or @summer-ji-eng if you have any further question. Thanks.

**Comment by rienswagerman** [comment]
I ran in to the same issue.

It might be aa good idea to update the example here:
https://cloud.google.com/tasks/docs/creating-http-target-tasks#creating_http_target_tasks
