### ISSUE TITLE
Authentication error if issuing multiple tasks at once

### ISSUE THREAD

**Issue by asktree** [googleapis/nodejs-tasks#283]
#### Environment details

  - OS: 
  - Node.js version: 10
  - npm version: 6.10
  - `@google-cloud/tasks` version: 1.4 (using v2beta3)

#### Steps to reproduce

  1. Make a cloud function that issues a working httpRequest task with an oidcToken
  2. Make a cloud function that issues a different working httpRequest task with an oidcToken
  3. Make a cloud function that combines the two, observe that the first task will create successfully and the second will produce an error similar to this: `"Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
    at GoogleAuth.getApplicationDefaultAsync (/srv/functions/node_modules/google-auth-library/build/src/auth/googleauth.js:161:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)" `

Note that I instantiate CloudTasksClient only once, I haven't tried doing it multiple times for each task, but my understanding is that this shouldn't matter.

**Comment by asktree** [comment]
Instantiating a new CloudTasksClient for each task fixed the issue.

**Comment by bcoe** [comment]
@asktree are you share a snippet of the code that was failing? You shouldn't need to create multiple clients, unless each client has different credentials.

**Comment by dusty** [comment]
I'm having the same problem, but I'm not trying to send multiple tasks, just a single one.  I'm running this inside cloud functions and listening for a bucket onFinalize event and sending a single http task to a cloud tasks queue with the payload.

It _seems_ that my function works fine when its first deployed.  Then after some time, I think after it scales to zero and then is re-triggered it always fails until I redeploy it.

<img width="1175" alt="Screen Shot 2019-10-05 at 8 18 47 AM" src="https://user-images.githubusercontent.com/792/66256995-cf1da980-e748-11e9-8539-a84702dec15d.png">

Does it make sense (in this context) to initialize the client on each invocation of cloud functions? 

Here is my code.

```js
const { v2beta3 } = require('@google-cloud/tasks')
const client = new v2beta3.CloudTasksClient()

const queue = body => {
  return client.createTask({
    parent: process.env.QUEUE_URL,
    task: {
      httpRequest: {
        httpMethod: 'POST',
        url: process.env.TASK_URL,
        headers: { 'Content-Type': 'application/json' },
        body: Buffer.from(JSON.stringify(body)),
        oidcToken: { serviceAccountEmail: process.env.SERVICE_ACCOUNT_EMAIL }
      }
    }
  })
}

exports.default = async file => {
  await queue(file)
  console.info(`DONE: ${file.name} queued`)
}

```

**Comment by dusty** [comment]
Perhaps related https://github.com/googleapis/google-auth-library-nodejs/issues/798

**Comment by bcoe** [comment]
@dusty I believe you're correct that this would have been related to #798.

It should now be addressed in the underlying library (see: [comments here](https://github.com/googleapis/google-auth-library-nodejs/issues/798#issuecomment-591622283).

It also might be worth rewriting code to lazy instantiate the client, like so:

```js
const { v2beta3 } = require('@google-cloud/tasks')
let client;
const queue = body => {
  if (!client) {
    client = new v2beta3.CloudTasksClient()
  }
  return client.createTask({
    parent: process.env.QUEUE_URL,
    task: {
      httpRequest: {
        httpMethod: 'POST',
        url: process.env.TASK_URL,
        headers: { 'Content-Type': 'application/json' },
        body: Buffer.from(JSON.stringify(body)),
        oidcToken: { serviceAccountEmail: process.env.SERVICE_ACCOUNT_EMAIL }
      }
    }
  })
}

exports.default = async file => {
  await queue(file)
  console.info(`DONE: ${file.name} queued`)
}
```

This will help ensure that no aync work is happening outside of the execution of your function.
