### ISSUE TITLE
Lower default max retries

### ISSUE THREAD

**Issue by ncjones** [googleapis/nodejs-tasks#294]
My GAE instance was failing to start after I included a call to `listQueues()` in my app's startup sequence because I forgot to enable the cloudtasks.googleapis.com service for the GCP project. This was trivial to fix but took a while to diagnose because the call was retrying and no failures were being logged. Changing the listQueues call to specify `{ maxRetries: 1 }` gave me an immediate useful error message. 

I would prefer that by default the library would use a lower max number of retries (and timeout for that matter) so that errors can be detected more easily.

**Comment by ncjones** [comment]
Also docs should say what the default values are. Currently the call options are all optional but defaults are not specified: https://googleapis.github.io/gax-nodejs/interfaces/CallOptions.html.

**Comment by callmehiphop** [comment]
@alexander-fenster @bcoe not really sure who to route this request to, but since everything here is generated it seems like we would want some one from the API team to chime in here.

**Comment by averikitsch** [comment]
Hi @ncjones 
Thank you for notifying us about the friction you faced. Would you mind adding these to our public issue tracker https://issuetracker.google.com?

In the future, to see the config of your queue, including max attempts, you can use:
```
gcloud tasks queues describe [QUEUE_NAME]
```
If the retry attempts don't need to be programmatically changed you can also use:
```
gcloud tasks queues update [QUEUE_NAME] --max-attempts=1
```

**Comment by ncjones** [comment]
@averikitsch I think you may have misunderstood the issue. The nodejs client SDK for cloud tasks was silently retrying the "list queues" API call forever, blocking my app from starting. The task queue max attempts configuration is not relevant in this scenario.

**Comment by ncjones** [comment]
@jayp maybe you have found a separate issue. 200ms timeout is probably too aggressive though.

**Comment by jayp** [comment]
> 
> 
> @jayp maybe you have found a separate issue. 200ms timeout is probably too aggressive though.

I was just messing around with timeout values to get a feel of what they are. I have filed a related issue #320

**Comment by sofisl** [comment]
Closing in lieu of https://github.com/googleapis/gax-nodejs/issues/1378, since that's where this issue would be resolved.
