### ISSUE TITLE
How can I use Cloud Tasks in frontend framework?

### ISSUE THREAD

**Issue by spider-hand** [googleapis/nodejs-tasks#311]
I am working on a project that is using Vue as frontend and Firebase as backend. And I was trying to use this client library in Vue component. However, this error happened.

> Error: {"clientConfig":{},"port":443,"servicePath":"cloudtasks.googleapis.com","scopes":["https://www.googleapis.com/auth/cloud-platform"]}You need to pass auth instance to use gRPC-fallback client in browser. Use OAuth2Client from google-auth-library.

I attach my code just in case.

```
import * as tasks from '@google-cloud/tasks'

      addTasks() {
        const client = new tasks.CloudTasksClient()

        const projectId = process.env.VUE_APP_FIREBASE_PROJECT_ID
        const queue = 'night'
        const location = process.env.VUE_APP_FIREBASE_LOCATION_ID
        const parent = client.queuePath(projectId, location, queue)

        const task = {
          httpRequest: {
            httpMethod: 'POST',
            url: 'https://${location}-${projectId}.cloudfunctions.net/...',
            scheduleTime: {
              seconds: ...,
            }, 
          }
        }

        const request = {
          parent: parent,
          task: task,
        }

        client.createTask(request)
      },
```

How can I solve this? Or doesn't this library support frontend framework? I am in trouble because I have been using Firebase for the project's backend and don't want to set up custom backend.

Currently I created a cloud function to create a cloud task and then the cloud task will trigger other cloud function. But I am wondering if I can create a task from frontend framework directly because my current way seems inefficient.

**Comment by bcoe** [comment]
Hey @spider-hand, there's a discussion [here](https://github.com/googleapis/google-cloud-node/issues/2933) as to how to get our gRPC libraries working in a front-end context :+1:
