### ISSUE TITLE
Use v2beta3 in TypeScript?

### ISSUE THREAD

**Issue by coolnalu** [googleapis/nodejs-tasks#319]
Does this package work with TypeScript well yet? Getting a bunch of incompatible type errors when trying to call the function in a typescript file.

**Comment by bcoe** [comment]
HEY @coolnalu 👋 there's actually an open PR [here](https://github.com/googleapis/nodejs-tasks/pull/317) that moves the library over to TypeScript, so this should have a much nicer TypeScript API surface in the new year.

**Comment by alexander-fenster** [comment]
And it was released!

**Comment by kirillgroshkov** [comment]
Sorry to resurrect an old issue, but it still doesn't export `types` in `package.json`. Are there plans to do so? Is there an issue to track this?

**Comment by alexander-fenster** [comment]
We are not going to export `types` in `package.json`, I believe it will be useless.  According to the [doc](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html), 

> Also note that if your `package.json` includes the `"files"` property the `"types"` property will be ignored. In that case you need to pass your main declaration file to the `"files"` property as well.

We do have `build/src/index.d.ts` right near the `build/src/index.js` which is the library entrypoint. It should just work.

@kirillgroshkov Can you give us more details why you would need the `"types"` property?
