### ISSUE TITLE
404: Instance Unavailable

### ISSUE THREAD

**Issue by bryanhpchiang** [googleapis/nodejs-tasks#339]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS: macOS 10.15
  - Node.js version: 12.6.0 (Node Engine 8 for Firebase)
  - npm version: 6.9.0
  - `@google-cloud/tasks` version: 1.7.1

#### Steps to reproduce

I'm trying to follow the README example, but I'm getting a ton of 404: Instance Unavailable errors followed by a bunch of retries. Not sure what's going on - even the simplest example isn't working.

**Comment by bryanhpchiang** [comment]
Found the error

**Comment by alectogeek** [comment]
@bryanhpchiang What was the problem in your case? I have same issue
