### ISSUE TITLE
http target task X-CloudTasks-TaskExecutionCount and other similar headers values are missing.

### ISSUE THREAD

**Issue by Adam-Edry** [googleapis/nodejs-tasks#344]
I'm not sure if this is the right place to submit an issue since this is more likely a problem with the cloud tasks service than this api. If I'm in the wrong place I'd appreciate if someone could point me to the right place.

Some of the headers outlined [here](https://cloud.google.com/tasks/docs/creating-http-target-tasks#handler) are always 0 or empty when they should not be.

For instance, X-CloudTasks-TaskExecutionCount even if the task has executed and failed multiple times. X-CloudTasks-TaskPreviousResponse is always 0 instead of the previous http response. X-CloudTasks-TaskRetryReason is always empty.

I realize those last two are optional but it seems like they should be populated in some of the cases I've seen.

In my case the http target is a cloud function url. Sometimes a task may fail due to a cloud function cold start and so I have to add retries to the task queue. However I would like to avoid retrying if the function itself failed. That is why I was trying to use the execution count header.

It seems as though even when the cloud function throws an error and the task retries, the execution count remains 0 and the other headers I mentioned are empty.

#### Environment details

  - OS: Win 10
  - Node.js version: `10.15.3`
  - npm version: `6.4.1`
  - `@google-cloud/tasks` version: `1.7.2`

#### Steps to reproduce

  1. Create a cloud function with a task handler that logs the request headers and then throws.
  2. Create a cloud tasks queue with max attempts set to 5.
  3. Add a task to the queue that targets the cloud function.
  4. Look at the logs to see that execution count is always 0 despite retry count going up and that the other headers are never used.

Again, if I'm posting in the wrong place I apologize. Hopefully you folks can help.

**Comment by bcoe** [comment]
@Adam-Edry If I'm following correctly, it sounds like the cloud function is not being executed with the headers you would expect, given that there have been retries?

I think it might also be worth [open an issue on the product issue tracker](https://issuetracker.google.com/savedsearches/5433985).

Thanks for the bug report.

**Comment by Adam-Edry** [comment]
@bcoe Thanks. I didn't think this was the right place for it but I didn't know where I should post the bug.
