### ISSUE TITLE
Automatically populate oidcToken.serviceAccountEmail if known via GKE metadata server

### ISSUE THREAD

**Issue by dpkirchner** [googleapis/nodejs-tasks#375]
**Is your feature request related to a problem? Please describe.**

I'm using the GKE Workload Identity feature to allow my applications to automatically authenticate with the Google Cloud APIs, and I'm loving it. I'd like to be able to automatically populate the `oidcToken` field with the default SA email address found in the GKE metadata server (put there by Workload Identity) rather than hardcode it in config files that have to be shipped with applications.

 **Describe the solution you'd like**

Ultimately I'd like to be able to create HTTP target tasks with an object something like:

```
const task = {
	httpRequest: {
		body: Buffer.from(JSON.stringify(result)).toString('base64'),
		headers: {'content-type': 'application/json'},
		httpMethod: 'POST',
		oidcToken: {serviceAccountEmail: 'default'},
		url,
	},
};
```

where `default` means "look up the service account in the metadata server". Alternatively or additionally, setting `serviceAccountEmail: 'inherit'` would use the same SA as is being used to enqueue the task (i.e. the account used by the CloudTasksClient instance).

The client probably shouldn't automatically fill in the service account email address if the `oidcToken` object is not set as some folks may not want to use the OIDC feature. Also, additional IAM rules are required to allow Cloud Tasks to use the service account (i.e. `roles/iam.serviceAccountUser`), which some folks may not want to grant.

 **Describe alternatives you've considered**

I'm hardcoding the service account email address in configs and using it in the task request.

 **Additional context**

Workload Identity: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity

**Comment by averikitsch** [comment]
The GKE environment has [Application Default Credentials](https://cloud.google.com/docs/authentication/production) that you could use to extract the service account email. Using the [Google Auth Library](https://github.com/googleapis/google-auth-library-nodejs) you could do something like:
```
const {GoogleAuth} = require('google-auth-library');
const auth = new GoogleAuth();
let cred = await auth.getCredentials();
let email = cred.client_email;
```

**Comment by dpkirchner** [comment]
This method works perfectly.

I started using something like that some time after creating this issue, but I forgot I had opened it, so I failed to return to comment/close. Sorry about that, and thank you for your reply!
