### ISSUE TITLE
INVALID_ARGUMENT: Invalid resource field value in the request.

### ISSUE THREAD

**Issue by tljesse** [googleapis/nodejs-tasks#394]
#### Environment details
* Firestore Functions 3.3.0
* Node.js version: 8
* npm version: 6.13.4
* @google-cloud/tasks version: 1.9.0

#### Error
Error: 3 INVALID_ARGUMENT: Invalid resource field value in the request.
    at Object.callErrorFromStatus (/srv/node_modules/@google-cloud/tasks/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Http2CallStream.call.on (/srv/node_modules/@google-cloud/tasks/node_modules/@grpc/grpc-js/build/src/client.js:96:33)
    at emitOne (events.js:121:20)
    at Http2CallStream.emit (events.js:211:7)
    at process.nextTick (/srv/node_modules/@google-cloud/tasks/node_modules/@grpc/grpc-js/build/src/call-stream.js:100:22)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)

#### Steps to Reproduce

I have been trying to create a task which I understand should be working with the latest version. I keep getting this error and have been unable to find the cause of it. I've tried the [sample code](https://github.com/googleapis/nodejs-tasks/blob/master/samples/createHttpTask.js) as well with the same error.

```typescript
const { CloudTasksClient } = require('@google-cloud/tasks');

const location = 'us-central1';
const queue = 'posts-ttl';

const tasksClient = new CloudTasksClient();
const queuePath: string = tasksClient.queuePath(PROJECT_ID, location, queue);

const url = `https://${location}-${PROJECT_ID}.cloudfunctions.net/callback`;

// let payload: ScheduledTaskPayload = {
// 	collection: 'scheduledPosts',
// 	doc_id: post._id,
// 	group_id: group._id
// };
const payload = 'Hello, world';

const seconds = 1000; //(+a[0]) * 60 * 60 + (+a[1]) * 60; 

const task = {
    httpRequest: {
      httpMethod: 'POST',
      url,
      body: Buffer.from(JSON.stringify(payload)).toString('base64'),
      // headers: {
      //   'Content-Type': 'application/json',
      // },
    },
    scheduleTime: {
      seconds: seconds
    }
 }
 console.log(task);

const [ response ] = await tasksClient.createTask({ queuePath, task });
```

Thanks for any help!

**Comment by tljesse** [comment]
I ended up adapting the sample code and got it running, I'm not really sure where the error ended up being in the above code. To get the callback to work with firestore functions I also needed to add the oidcToken and within my IAM settings I added the Cloud Functions Invoker role to the same member running the function.

```typescript
async function createHttpTask(
  project: string, // Your GCP Project id
  queue: string, // Name of your Queue
  location: string, // The GCP region of your queue
  url: string, // The full url path that the request will be sent to
  payload: ScheduledTaskPayload, // The task HTTP request body
  email: string, // The service account email
  inSeconds: number = 0 // Delay in task execution
) {

  // Instantiates a client.
  const client = new CloudTasksClient();


  // Construct the fully qualified queue name.
  const parent = client.queuePath(project, location, queue);

  const task: any = {
    httpRequest: {
      httpMethod: 'POST',
      url,
      headers: {
        'Content-Type': 'application/json',
      },
      oidcToken: {
        serviceAccountEmail: email,
      },
    },
  };

  if (payload) {
    task.httpRequest.body = Buffer.from(JSON.stringify(payload)).toString('base64');
  }

  if (inSeconds) {
  	let midnight = new Date();
  	midnight.setHours(0,0,0,0);
    // The time when the task is scheduled to be attempted.
    task.scheduleTime = {
      seconds: inSeconds + midnight.getTime() / 1000,
    };
  }

  // Send create task request.
  // console.log('Sending task:');
  // console.log(task);
  const request = {parent, task};
  const [response] = await client.createTask(request);

  //console.log(response);
  console.log(`Created task ${response.name}`);
  // [END cloud_tasks_create_http_task]
}
```

**Comment by averikitsch** [comment]
@tljesse , you are not using the correct inputs to the `createTask` method. The correct input object would have keys, `parent` and `task`.
This line `const [ response ] = await tasksClient.createTask({ queuePath, task });` expanded looks like:
```
const [ response ] = await tasksClient.createTask({ 
  queuePath: queuePath, 
  task: task
});
```
But should be:
```
const [ response ] = await tasksClient.createTask({ 
  parent: queuePath, 
  task: task
});
```
