### ISSUE TITLE
How to use insecure connection

### ISSUE THREAD

**Issue by ottob** [googleapis/nodejs-tasks#462]
Im trying to use a [local emulator](https://github.com/aertje/cloud-tasks-emulator) for Cloud Tasks that requires an insecure connection.

Im trying to construct a client like this:
"@google-cloud/tasks" is v2.1.0
"@grpc/grpc-js" is v1.1.6
```ts
import { CloudTasksClient } from '@google-cloud/tasks'
import { credentials } from '@grpc/grpc-js'

const client = new CloudTasksClient({
      servicePath: 'localhost',
      port: 8123,
      sslCreds: credentials.createInsecure(),
    })
```
But get the following error:
```
error TS2322: Type 'import("/Users/me/myproj/node_modules/@grpc/grpc-js/build/src/channel-credentials").ChannelCredentials' is not assignable to type 'import("/Users/me/myproj/node_modules/google-gax/node_modules/@grpc/grpc-js/build/src/channel-credentials").ChannelCredentials'.
  Property 'callCredentials' is protected but type 'ChannelCredentials' is not a class derived from 'ChannelCredentials'.

20       sslCreds: credentials.createInsecure(),
         ~~~~~~~~

Found 1 error.
```
How can this be done?

**Comment by bcoe** [comment]
@ottob I wouldn't expect that you need to instantiate the grpc credentials yourself. Could you try setting the `apiEndpoint` value to the emulator address, including port?

**Comment by ottob** [comment]
Do you mean like this?
```ts
const client = new CloudTasksClient({
      servicePath: 'localhost',
      port: 8123,
      //sslCreds: credentials.createInsecure(),
    })
```
Then I get his error from the call to `createTask`: `Error: 14 UNAVAILABLE: No connection established`

**Comment by spideythewebhead** [comment]
Hello, I have a bit of the same problem, I am using the emulator suite for functions and firestore , but I can't set a task, I am getting error 4 ( i don't have access to the log yet I will update) . Do I need to setup the credentials for the client; or I need to use the emulator @ottob uses? Thanks

**Comment by AlexanderArvidsson** [comment]
I fixed this by making sure that `@grpc/grpc-js` matched the exakt same version as `google-gax`s dependency, which I found out by inspecting the `yarn.lock` file to be `1.1.8`. 

After that, it worked fine. You can also look in `node_modules/google-gax/node_modules/@grpc/grpc-js/package.json` to see which version you need.

**Comment by harmon** [comment]
I too am getting this error @ottob. I'll post here if I figure it out:
```
const client = new CloudTasksClient({ apiEndpoint: 'localhost', port: 8123 });

Error: 14 UNAVAILABLE: No connection established
    at Object.callErrorFromStatus (/server/node_modules/@grpc/grpc-js/src/call.ts:81:24)
    at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/src/client.ts:334:36)
    at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:34)
    at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
    at /server/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 14,
  details: 'No connection established',
  metadata: Metadata { internalRepr: Map {}, options: {} }
}
```

**Comment by AlexanderArvidsson** [comment]
> I too am getting this error @ottob. I'll post here if I figure it out:
> 
> ```
> const client = new CloudTasksClient({ apiEndpoint: 'localhost', port: 8123 });
> 
> Error: 14 UNAVAILABLE: No connection established
>     at Object.callErrorFromStatus (/server/node_modules/@grpc/grpc-js/src/call.ts:81:24)
>     at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/src/client.ts:334:36)
>     at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:34)
>     at Object.onReceiveStatus (/server/node_modules/@grpc/grpc-js/src/client-interceptors.ts:387:48)
>     at /server/node_modules/@grpc/grpc-js/src/call-stream.ts:249:24
>     at processTicksAndRejections (internal/process/task_queues.js:75:11) {
>   code: 14,
>   details: 'No connection established',
>   metadata: Metadata { internalRepr: Map {}, options: {} }
> }
> ```

You should not use `apiEndpoint`. Just use it as follows:
```js
const client = isLocalEmulator
  ? new CloudTasksClient({
      servicePath: 'localhost',
      port: 9090,
      sslCreds: credentials.createInsecure()
    })
  : new CloudTasksClient();
```
Use the correct port for your use case.

You also need to make sure you are **using the same version of grpcjs across your project**, Please look at my comment https://github.com/googleapis/nodejs-tasks/issues/462#issuecomment-750417668 above.
You can also use a resolution in your package.json file to force the version to the same one.

**Comment by harmon** [comment]
Thanks @AlexanderArvidsson! I totally missed the `sslCreds: credentials.createInsecure()` part from the original post. This now works great. The grpcjs version was correctly installed originally when I installed this library, and it's now submitting my tasks. 

I verified it worked originally with the sample Python code, which had good documentation on how to send insecure GRPC calls, but the docs for the nodejs library are a bit lacking in that area. I'm glad I re-read your post and the original one to glean what I need to do to get it working.

Much appreciated, cheers!

**Comment by averikitsch** [comment]
Closing. If the issue persists please reopen.
