### ISSUE TITLE
Time to process task, dispatchDeadline

### ISSUE THREAD

**Issue by teebu** [googleapis/nodejs-tasks#487]
I created the cloud task to call HTTP, in the documentation it says the default timeout is 10 minutes, but can be set to 30 minutes. 

When my task runs, it times out at 60 seconds. In the task queue page I see:

```
Dispatch time
Nov 19, 2020, 9:07:52 PM
Time late
0.006881s
Time to process task
60.064613s
Status code
13 (INTERNAL)
Reason to retry
INTERNAL(13): HTTP status code 502
```

How to I change the time? Is it set during task creation or queue creation?

**Comment by teebu** [comment]
It turns out the 60 sec timeout was caused by firebase 60 second limit on cloud functions. It wasn't obvious because I use both google and firebase for cloud functions. 

But, How do I set the timeout to be 30 minutes? I know the option is called dispatchDeadline, just don't know how or where to pass it? I'm using nodejs with google sdk.

**Comment by bcoe** [comment]
@teebu are you using firebase functions? you should be able to specify a longer timeout in configuration:

https://firebase.google.com/docs/functions/manage-functions

It has a maximum timeout of 540 seconds however.

**Comment by teebu** [comment]
https://firebase.google.com/docs/hosting/functions

```
Note: Firebase Hosting is subject to a 60-second request timeout. Even if you configure your HTTP function with a longer request timeout, you'll still receive an HTTP status code 504 (request timeout) if your function requires more than 60 seconds to run. To support dynamic content that requires longer compute time, consider using an App Engine flexible environment.
```

**Comment by averikitsch** [comment]
Re-open if necessary
