### ISSUE TITLE
Memory Exhausted

### ISSUE THREAD

**Issue by easa** [googleapis/nodejs-tasks#501]
By running this function 10 times, the memory in use would be 2000mg! I used the optimum approach, suggested by the official samples, and I think the problem is with the package since the memory usage is normal on exceptions.
On local machine it runs and eat up a lot of memory but on cloud function it just throw memory limit error!
``` js
import { https } from 'firebase-functions';
import express from 'express';
import { CloudTasksClient } from '@google-cloud/tasks';

const router = express();
router.get('/', cloudFunctionExpress);

export const testFunctionForTaskMemoryUsage = https.onRequest(router);

async function cloudFunctionExpress(req, res) {
  const tasks = Array(100).fill({ id: 10 });
  const queue = 'queueName';
  const url = 'url';
  const promises = tasks.map((task: any) => pushTask(queue, url, { queue, task }));
  Promise.all(promises).then(function afterPromises() {
    res.status(200).send(`All task has been made for total of #${promises?.length}`);
  }).catch(function promiseCatch(err) {
    res.status(500).send(`error #${promises?.length}, err: ${JSON.stringify(err)}`);
  });
}

const pushTask = async (queue, url, body, inSeconds) => {
  const client = new CloudTasksClient();
  const payload = JSON.stringify(body);
  const parent = client.queuePath('projectId', 'location', queue);
  const task = {
    httpRequest: {
      httpMethod: 'POST',
      headers: {
        'content-type': 'application/json',
      },
      url,
      body: Buffer.from(payload).toString('base64'),
    },
  };
  if (inSeconds) {
    // The time when the task is scheduled to be attempted.
    task.scheduleTime = {
      seconds: inSeconds + Date.now() / 1000,
    };
  }
  // Send create task request.
  const request = { parent, task };
  const [response] = await client.createTask(request)
    .then((responses) => responses)
    .catch((_err) => []);
  return response?.name;
};
```

**Comment by ace-n** [comment]
cc @samtstern @bcoe

**Comment by samtstern** [comment]
I don't think this has anything to do with `firebase-functions`since that's only being used to export the `https` handler.

While I'm here though:

  * @ace-n is correct, you need to add `return` there or your function will probably exit early
  * Creating `const client = new CloudTasksClient();` in a tight loop seems like it would contribute to high memory usage. You should create that client outside the loop and re-use it.
  * You can always raise the memory limit on this function, see the [docs](https://firebase.google.com/docs/functions/manage-functions) for more information. Node.js runtimes support up to 4GB of memory which should be more than enough. Of course that will increase your costs so you should try to reduce the memory usage as much as possible first.

**Comment by bcoe** [comment]
@samtstern one thing that jumps out at me is that you're instantiating the client in each request, I would avoid doing this, and write the example code like this:

```js
import { https } from 'firebase-functions';
import express from 'express';
import { CloudTasksClient } from '@google-cloud/tasks';

const router = express();
router.get('/', cloudFunctionExpress);

export const testFunctionForTaskMemoryUsage = https.onRequest(router);

async function cloudFunctionExpress(req, res) {
  const tasks = Array(100).fill({ id: 10 });
  const queue = 'queueName';
  const url = 'url';
  const promises = tasks.map((task: any) => pushTask(queue, url, { queue, task }));
  Promise.all(promises).then(function afterPromises() {
    res.status(200).send(`All task has been made for total of #${promises?.length}`);
  }).catch(function promiseCatch(err) {
    res.status(500).send(`error #${promises?.length}, err: ${JSON.stringify(err)}`);
  });
}


let client;
const pushTask = async (queue, url, body, inSeconds) => {
  if (!client) {
    client = new CloudTasksClient();
  }
  const payload = JSON.stringify(body);
  const parent = client.queuePath('projectId', 'location', queue);
  const task = {
    httpRequest: {
      httpMethod: 'POST',
      headers: {
        'content-type': 'application/json',
      },
      url,
      body: Buffer.from(payload).toString('base64'),
    },
  };
  if (inSeconds) {
    // The time when the task is scheduled to be attempted.
    task.scheduleTime = {
      seconds: inSeconds + Date.now() / 1000,
    };
  }
  // Send create task request.
  const request = { parent, task };
  const [response] = await client.createTask(request)
    .then((responses) => responses)
    .catch((_err) => []);
  return response?.name;
};
```

**Comment by samtstern** [comment]
@bcoe I think you meant to mention @easa

**Comment by bcoe** [comment]
@samtstern 👍 my bad, @easa as @samtstern also suggests, try pulling out your client initialization into the global.

**Comment by easa** [comment]
@ace-n Thanks. The "return promise" is necessary to terminate "database trigger functions" but won't do anything in cloud functions, sending a response would terminate a cloud function.

@samtstern Thanks, yes it isn't the library.

@bcoe you gave me a big hint and the issue of memory overuse is that the code makes a lot of instances of the 
CloudTasksClient so I just needed to create an instance of the cloud task client outside of that function that I call it 100 times. Thank you so much.
