### ISSUE TITLE
INVALID_ARGUMENT: Location 'europe-west1' is not a valid location

### ISSUE THREAD

**Issue by JTInfinite** [googleapis/nodejs-tasks#509]
#### Environment details

  - OS: Google Cloud Functions
  - Node.js version: 12
  - npm version: 6.14.10
  - `@google-cloud/tasks` version: 2.3.0

#### Steps to reproduce

```
const functions = require('firebase-functions');
const {CloudTasksClient} = require("@google-cloud/tasks");
const admin = require('firebase-admin');

const client = new CloudTasksClient({ fallback: true });

// Omit the actual triggered function

async function createHttpTasks(session) {
  const project = "XXXXX"; // These match my project and queue id/name
  const queue = "XXXXXX";
  const location = "europe-west1";
  
  // Construct the fully qualified queue name.
  const parent = client.queuePath(project, location, queue);
  
  // Do stuff
  
  const requestCheck = {parent, taskCheckIn};
  await client.createTask(requestCheck);
}
```

Hello!

My error code after calling the above (which is shortened for brevity) within a cloud function is:

`Error: 3 INVALID_ARGUMENT: Location 'europe-west1' is not a valid location. Use ListLocations to list valid locations.`

If I change to location to "us-central" for example, the error code changes to:

`Error: 3 INVALID_ARGUMENT: Location must equal europe-west1 because the App Engine app that is associated with this project is located in europe-west1`

I have had a look on stackoverflow for similar but came up short. I left a comment on this question to see if the op had any luck:

https://stackoverflow.com/questions/60930970/google-cloud-tasks-location-europe-west1-is-not-a-valid-location

Where am I going wrong? 

Thanks!

JT

**Comment by averikitsch** [comment]
To reproduce I've tried creating an  App Engine app in europe-west and a task queue in europe-west1. 
I've found setting `{ fallback: true }` for the client throws this error. This is the default so it doesn't need to be specified. Can you remove this and try again?

**Comment by JTInfinite** [comment]
@averikitsch thanks for the response.

I removed the fallback setting as suggested. This is the new error:

`Error: 3 INVALID_ARGUMENT: Task.payload_type is not set.
    at Object.callErrorFromStatus (/workspace/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
    at Object.onReceiveStatus (/workspace/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
    at /workspace/node_modules/@grpc/grpc-js/build/src/call-stream.js:145:78
    at processTicksAndRejections (internal/process/task_queues.js:79:11) `


More details on the function:


    const project = "XXXXX";
    const queue = "XXXXX";
    const location = "europe-west1";

    // Construct the fully qualified queue name.
    const parent = client.queuePath(project, location, queue);

    const payload = JSON.stringify(session.session) // session is the function param



    const taskPriorReminder = {
        httpRequest: {
            httpMethod: "POST",
            headers: {
                'Content-Type': 'application/json',
            },
            url: "https://us-central1-xxxx/xxxx",
            body: Buffer.from(payload).toString("base64"),
        },
        scheduleTime: {
            seconds: session.session.secondsToPriorReminder,
        }
    };


    const taskCheckIn = {
        httpRequest: {
            httpMethod: "POST",
            headers: {
                'Content-Type': 'application/json',
            },
            url: "https://us-central1-xxxx/xxxx",
            body: Buffer.from(payload).toString("base64"),
        },
        scheduleTime: {
            seconds: session.session.secondsToCheckIn,
        }
    };

    
    const taskAlert = {
        httpRequest: {
            httpMethod: "POST",
            headers: {
                'Content-Type': 'application/json',
            },
            url: "https://us-central1-xxxx/xxxx",
            body: Buffer.from(payload).toString("base64"),
        },
        scheduleTime: {
            seconds: session.session.secondsToAlert,
        }
    };
    
    await client.createTask({parent, taskPriorReminder});

    await client.createTask({parent, taskCheckIn});

    await client.createTask({parent, taskAlert});

    return // end function`

**Comment by averikitsch** [comment]
The request does not have the correct inputs. `createTask` is looking for an object with `parent` and `task` keys.  For example, this code `await client.createTask({parent, taskPriorReminder});` needs to be updated to `await client.createTask({parent, task: taskPriorReminder});`.

**Comment by JTInfinite** [comment]
Doh! Thanks for your assistance. It's now working.
