### ISSUE TITLE
Error: 13 INTERNAL: Request message serialization failure: invalid encoding

### ISSUE THREAD

**Issue by VladimirMikulic** [googleapis/nodejs-tasks#606]
1) Is this a client library issue or a product issue?
- Client library issue

2) Did someone already solve this?
  - As far as I know, no.

3) Do you have a support contract?
- No

#### Environment details
- OS: KDE Neon 5.24
- Node.js version: 16.14.0
- npm version: 8.0.0
- `@google-cloud/tasks` version: 2.5.0

#### Steps to reproduce

Example taken from: https://github.com/googleapis/nodejs-tasks/issues/91#issuecomment-442656101
(our code also looks like this)

```js
const { CloudTasksClient } = require('@google-cloud/tasks');
const client = new CloudTasksClient();

// content of the task
const payload = {
  foo: 'bar',
};

// configuration for the task
const request = {
  parent: client.queuePath('my-project', 'my-location', 'my-batch'),
  task: {
    appEngineHttpRequest: {
      httpMethod: 'POST',
      relativeUri: '/endpoint',
      body: Buffer.from(JSON.stringify(payload)).toString('base64'),
      headers: {
        'Content-Type': 'application/json',
      },
    },
  },
};

return client.createTask(request);
```

#### Error

Error: 13 INTERNAL: Request message serialization failure: invalid encoding

Thanks!

**Comment by grayside** [comment]
Hello @VladimirMikulic,

Thanks for opening a detailed issue with your problem.

Looking at this code, and comparing to the official guidance on https://cloud.google.com/tasks/docs/creating-appengine-tasks, I may see the problem:

You are base64 encoding your JSON, which means it should not use the `application/json` content type. If you removing that content type or the base64 encoding, I expect this error will be resolved.

Please reopen the issue if you have further problems, and comment back for future searchers with your discoveries!

**Comment by metadiego** [comment]
I ran into this same issue, but had a different conclusion.

Initially tried this (which did not work): 
`
  const task: protos.google.cloud.tasks.v2.ITask = {
    appEngineHttpRequest: {
      httpMethod: 'POST',
      relativeUri: '/full-nft-data-by-file',
      body: JSON.stringify({fileName: fileName}).,
      headers: {
        'Content-Type': 'application/json',
      }
    },
`

After checking GCP Task queue, with above setup, the content-type is not set to 'application/json'. 

So instead, I tried this, which DOES work:

`
  const task: protos.google.cloud.tasks.v2.ITask = {
    appEngineHttpRequest: {
      httpMethod: 'POST',
      relativeUri: '/full-nft-data-by-file',
      body: Buffer.from(JSON.stringify({fileName: fileName})).toString("base64"),
      headers: {
        'Content-Type': 'application/json',
      }
    },
`

Here are some possibly relevant project dependencies:
`
    "@google-cloud/tasks": "^3.0.0",
    "typescript": "^4.0.0"
`
