### ISSUE TITLE
INVALID_ARGUMENT: Queue.queue_type must be set

### ISSUE THREAD

**Issue by pyitphyoaung** [googleapis/nodejs-tasks#95]
#### Environment details

  - OS: macOS Mojave (10.14)
  - Node.js version: 8.12.0
  - npm version:
  - `@google-cloud/tasks` version: 0.2.2

#### Steps to reproduce

The following code which is based on sample from [createQueue](https://cloud.google.com/nodejs/docs/reference/tasks/0.2.x/v2beta3.CloudTasksClient#createQueue) produces an "INVALID_ARGUMENT: Queue.queue_type must be set." error:

```sh
const tasks = require('@google-cloud/tasks');

var client = new tasks.v2beta3.CloudTasksClient({
  // optional auth parameters.
});

var request = {
  parent: client.locationPath('[project]', '[location]'),
  queue: {
        name: `projects/[project]/locations/[location]/queues/[queue-id]`,
        rateLimits: { maxDispatchesPerSecond: 500 },
        retryConfig: { maxAttempts: 1 }
  },
};

client.createQueue(request)
  .then(responses => {
    var response = responses[0];
    // doThingsWith(response)
  })
  .catch(err => {
    console.error(err);
  });
```

**Comment by dinigo** [comment]
I don't want to start a "me too" chain reaction, but... me too. I fount the same exact error.

 - OS: macOS High Sierra (10.13)
 - Node.js version: 10.13
 - yarn version: 1.10.1
 - @google-cloud/tasks version: 0.2.2

If you try wit the `v2beta2` you will find out similar error

```javascript
const tasks = require('@google-cloud/tasks');
const client = new tasks.v2beta2.CloudTasksClient();
const PROJECT_ID = '[project]';
const LOCATION_ID = '[location]'; //europe-west1
(async () => {
  const request = {
    parent: client.locationPath(PROJECT_ID, LOCATION_ID),
    queue: {
      name: client.queuePath(PROJECT_ID, LOCATION_ID, 'queue-' + (+new Date())),
    },
  };
  try {
    const response = await client.createQueue(request);
    console.log(response);
  } catch (err) {
    console.error(err);
  }
})();

```

*Error:  Queue.target_type must be set.*
```
{
    Error: 3 INVALID_ARGUMENT: Queue.target_type must be set.
      at Object.exports.createStatusError (...node_modules/grpc/src/client_interceptors.js:1188:28)
      at InterceptingListener._callNext (.../node_modules/grpc/src/client_interceptors.js:564:42)
      at InterceptingListener.onReceiveStatus (.../node_modules/grpc/src/client_interceptors.js:614:8)
      at callback (.../node_modules/grpc/src/client_interceptors.js:841:24)
    code: 3,
    metadata:
      Metadata {
        _internal_repr: { 'grpc-server-stats-bin': [Array] }
      },
  details: 'Queue.target_type must be set.' 
}
```

**Comment by dinigo** [comment]
There's no reference to the `queue_type` in the [documentation](https://cloud.google.com/nodejs/docs/reference/tasks/0.2.x/google.cloud.tasks.v2beta3), nor in the [REST](https://cloud.google.com/tasks/docs/reference/rest/v2beta3/projects.locations.queues/create) documentation for the `queue_type`.

When you follow the docs for the `createQueue` method it requires a `query` object, which has an RCP type [like so](https://cloud.google.com/nodejs/docs/reference/tasks/0.2.x/google.cloud.tasks.v2beta3#.Queue):

> A queue is a container of related tasks. Queues are configured to manage how those tasks are dispatched. Configurable properties include rate limits, retry options, _**queue types**_, and others.

If you read closely you'll find that `Queue` has a property called `appEngineHttpQueue` of type [AppEngineHttpQueue](https://cloud.google.com/nodejs/docs/reference/tasks/0.2.x/google.cloud.tasks.v2beta3.html#.AppEngineHttpQueue). On the other hand, the documentation for the [message sent to the API](https://github.com/googleapis/nodejs-tasks/blob/923cd1d4bb062f3fcfb1a3c744cd13009e05e8b5/protos/google/cloud/tasks/v2beta3/queue.proto#L97) (the _.proto_) says:
```proto
oneof queue_type {
  AppEngineHttpQueue app_engine_http_queue = 3;
}
```
`AppEngineHttpQueue` is the only value in the `oneof`. But setting the value in the queue definition doesn't work either:
```javascript
  const request = {
    parent: client.locationPath(PROJECT_ID, LOCATION_ID),
    queue: {
      name: client.queuePath(PROJECT_ID, LOCATION_ID, 'queue-' + (+new Date())),
      queue_type: 3 // app_engine_http_queue doesn't work either
    },
  };
```

**Comment by kinwa91** [comment]
Hi! Can you try using camelCase for `queueType`?

**Comment by dinigo** [comment]
> Hi! Can you try using camelCase for `queueType`?
@kinwa91, It throws the same error.

I've tried the REST API and it also throws the same error. I'm beginning to doubt this is due to the library. Maybe they've changed something in the API to reinforce it.

![image](https://user-images.githubusercontent.com/3038962/49069762-5f868600-f22a-11e8-989d-64fa912b5435.png)

**Comment by tarasBilobran** [comment]
for creating task queue you need to specify service for which task queue should be created. Payload should have next format
`
{
  "name": "projects/project_id/location/location_id/queues/que_id"
  "appEngineHttpQueue": {
    "appEngineRoutingOverride": {
      "service": "default" # or your service name
    }
}
`

**Comment by tarasBilobran** [comment]
for creating task queue you need to specify service for which task queue should be created. Payload should have next format
{ "name": "projects/project_id/location/location_id/queues/que_id" "appEngineHttpQueue": { "appEngineRoutingOverride": { "service": "default" # or your service name } }

**Comment by tarasBilobran** [comment]
@dinigo, actually one man helped me with this, and as you said it's not documented so i was confused just like you.

**Comment by JustinBeckwith** [comment]
@alexander-fenster this is similar to the other one.  There's basically nothing in the proto definitions that tell us what fields in the create queue payload are actually required.  Is this something you know how to change?  I have a sample over in #142 that should help a little, but really we need these APIs to be a little more self-documenting.

**Comment by nthgol** [comment]
This sounds like a bug. why would you require specifying an override?

**Comment by averikitsch** [comment]
Closing due to bug age. Please re open if the issue persists.
